# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
    nodejs: "24"
  jobs:
    pre_install:
      - python -m pip install pdm
    install:
      - npm --prefix js/ ci
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install --with docs
    pre_build:
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm run build-js-docs
      # rm this once the config hooks PR is merged
      - 'echo "config_dir: docs/assets/pipelines" > noob_config.yaml'