# Changes here will be overwritten by Copier
_src_path: templates/nobes
author_email: sneakers-the-rat@protonmail.com
author_name: sneakers-the-rat
description: OS interaction - notifications, clipboards, etc.
package_name: os
