from collections.abc import Callable
from typing import Any

from noob.testing.assets import AnyAsset, Initializer, LifecycleCounter, counter, counter_cm
from noob.testing.nodes import (
    CountSource,
    CountSourceDecor,
    DynamicSignals,
    InitCounter,
    Multiply,
    Now,
    NumberToLetterCls,
    StatefulMultiply,
    UnannotatedGenerator,
    Volume,
    VolumeProcess,
    async_error,
    concat,
    count_source,
    cycle,
    dictify,
    divide,
    error,
    exclaim,
    fast_forward,
    increment,
    inject_epoch,
    inject_eventmap,
    input_party,
    jump,
    just_wait,
    letter_source,
    long_add,
    multi_concat,
    multi_words_source,
    multiply,
    number_to_letter,
    passthrough,
    repeat,
    rewind,
    sporadic_word,
    sporadic_word_noevent,
    switch,
    this_or_that,
    word_counts,
    word_source,
    zip_iter,
)

__all__ = [
    "AnyAsset",
    "DynamicSignals",
    "async_error",
    "concat",
    "count_source",
    "cycle",
    "dictify",
    "divide",
    "error",
    "exclaim",
    "letter_source",
    "long_add",
    "multiply",
    "number_to_letter",
    "passthrough",
    "repeat",
    "sporadic_word",
    "sporadic_word_noevent",
    "word_counts",
    "word_source",
    "multi_concat",
    "multi_words_source",
    "CountSource",
    "Multiply",
    "VolumeProcess",
    "Volume",
    "InitCounter",
    "Now",
    "NumberToLetterCls",
    "StatefulMultiply",
    "UnannotatedGenerator",
    "counter",
    "counter_cm",
    "CountSourceDecor",
    "LifecycleCounter",
    "increment",
    "inject_epoch",
    "inject_eventmap",
    "input_party",
    "fast_forward",
    "rewind",
    "jump",
    "just_wait",
    "switch",
    "this_or_that",
    "zip_iter",
    "Initializer",
]


def __getattr__(name: str) -> Callable:
    """
    When we just get any old random node, e.g. in the docs for illustration,
    just create some passthrough function
    """

    def _passthrough(**kwargs: Any) -> Any:
        return kwargs

    return _passthrough
