from __future__ import annotations
from typing import Any, TypeAlias, TypedDict

from noob_core._types import SorterState

_ReadyNodes: TypeAlias = list[tuple[Epoch, str]]
_EpochSegment: TypeAlias = tuple[str, int]
_WireEpoch: TypeAlias = list[int | _EpochSegment] | int
_Item: TypeAlias = str | tuple[str, str]

class Scheduler:
    epoch_log: set[int]
    subepochs: dict[Epoch, set[Epoch]]

    def __init__(
        self, nodes: list[tuple[str, bool, bool | None]], edges: list[tuple[str, str, str, bool]]
    ): ...
    def add_epoch(self) -> Epoch: ...
    def add_epoch_at(self, epoch: Epoch) -> Epoch: ...
    def is_active(self) -> bool: ...
    def is_active_at(self, epoch: Epoch) -> bool: ...
    def epoch_completed(self, epoch: Epoch) -> bool: ...
    def get_ready(self) -> _ReadyNodes: ...
    def get_ready_at(self, epoch: Epoch) -> _ReadyNodes: ...
    def node_is_ready(self, node: str, epoch: Epoch, subepochs: bool) -> bool: ...
    def node_is_done(self, node: str, epoch: Epoch) -> bool: ...
    def done(
        self, epoch: Epoch, node_id: str, signal: str | None = None, with_signals: bool = True
    ) -> list[Epoch]: ...
    def expire(
        self,
        epoch: Epoch,
        node_id: str,
        signal: str | None = None,
        with_signals: bool = True,
        unlock_optionals: bool = True,
    ) -> list[Epoch]: ...
    def end_epoch(self, epoch: Epoch) -> list[Epoch]: ...
    def update(self, events: list[tuple[Epoch | int, str, str, bool]]) -> list[Epoch]: ...
    def first_active_epoch(self) -> Epoch | None: ...
    def sources_finished(self, epoch: Epoch | int) -> bool: ...
    def has_cycle(self) -> bool: ...
    def generations(self) -> list[list[str]]: ...
    def source_nodes(self) -> list[str]: ...
    def upstream_nodes(self, node: str) -> set[str]: ...
    def get_epoch_state(self, epoch: Epoch) -> SorterState: ...

class Epoch:
    root: int
    root_epoch: Epoch
    is_root: bool
    parents: list[Epoch]
    parent: Epoch | None
    leaf: _EpochSegment | None

    def __init__(self, root: int, path: list[_EpochSegment] = []): ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: Epoch) -> bool: ...
    def __gt__(self, other: Epoch) -> bool: ...
    def __le__(self, other: Epoch) -> bool: ...
    def __ge__(self, other: Epoch) -> bool: ...
    def __hash__(self) -> int: ...
    def __truediv__(self, other: _EpochSegment) -> Epoch: ...
    def __add__(self, other: int) -> Epoch: ...
    def __sub__(self, other: int) -> Epoch: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: int) -> _EpochSegment: ...
    def make_subepochs(self, node: str, n: int) -> list[Epoch]: ...
    def to_wire(self) -> _WireEpoch: ...
    @staticmethod
    def from_wire(wire: _WireEpoch) -> Epoch: ...
