from typing import Any, TypeAlias

_Epoch: TypeAlias = list[tuple[str, int]]
_ReadyNodes: TypeAlias = list[tuple[_Epoch, str]]

class Scheduler:
    def __init__(
        self, nodes: list[tuple[str, bool, bool | None]], edges: list[tuple[str, str, str, bool]]
    ): ...
    def add_epoch(self) -> _Epoch: ...
    def add_epoch_at(self, epoch: _Epoch) -> _Epoch: ...
    def is_active(self) -> bool: ...
    def is_active_at(self, epoch: _Epoch) -> bool: ...
    def epoch_completed(self, epoch: _Epoch) -> bool: ...
    def get_ready(self) -> _ReadyNodes: ...
    def get_ready_at(self, epoch: _Epoch) -> _ReadyNodes: ...
    def done(
        self, epoch: _Epoch, node_id: str, signal: str | None = None, with_signals: bool = True
    ) -> list[_Epoch]: ...
    def expire(
        self,
        epoch: _Epoch,
        node_id: str,
        signal: str | None = None,
        with_signals: bool = True,
        unlock_optionals: bool = True,
    ) -> list[_Epoch]: ...
    def end_epoch(self, epoch: _Epoch) -> list[_Epoch]: ...
    def update(self, events: list[tuple[_Epoch | int, str, str, bool]]) -> list[_Epoch]: ...
    def first_active_epoch(self) -> _Epoch | None: ...
    def sources_finished(self, epoch: _Epoch | int) -> bool: ...

_EpochSegment: TypeAlias = tuple[str, int]
_WireEpoch: TypeAlias = list[int | _EpochSegment] | int

class Epoch:
    root: int
    parents: list[Epoch]

    def __init__(self, root: int, path: list[_EpochSegment] = []): ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: Epoch) -> bool: ...
    def __gt__(self, other: Epoch) -> bool: ...
    def __le__(self, other: Epoch) -> bool: ...
    def __ge__(self, other: Epoch) -> bool: ...
    def __hash__(self) -> int: ...
    def __truediv__(self, other: _EpochSegment) -> Epoch: ...
    def __add__(self, other: int) -> Epoch: ...
    def __sub__(self, other: int) -> Epoch: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: int) -> _EpochSegment: ...
    def make_subepochs(self, node: str, n: int) -> list[Epoch]: ...
    def to_wire(self) -> _WireEpoch: ...
    @staticmethod
    def from_wire(wire: _WireEpoch) -> Epoch: ...
