import sys
from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

if sys.version_info < (3, 12):
    from typing_extensions import TypedDict
else:
    from typing import TypedDict


class Event(TypedDict):
    """
    Container for a single value returned from a single :meth:`.Node.process` call
    """

    id: int
    """Unique ID for each event"""
    timestamp: datetime
    """Timestamp of when the event was received by the :class:`.TubeRunner`"""
    node_id: str
    """ID of node that emitted the event"""
    signal: str
    """name of the signal that emitted the event"""
    epoch: int
    """Epoch number the event was emitted in"""
    value: Any
    """Value emitted by the processing node"""


class MetaEventType(StrEnum):
    """
    Do not go into EventStore

    """

    NodeReady = "NodeReady"
    EpochEnded = "EpochEnded"


class MetaEvent(Event):
    """
    All events generated by internal

    """

    # mypy doesn't allow narrowing types in typed dicts?
    node_id: Literal["meta"]  # type: ignore
    signal: MetaEventType  # type: ignore


class NoEvent:
    """
    Signifier for no event emitted

    """

    pass
