name: Lint JS
on:
  push:
    branches:
      - main
    paths:
      - js/**
      - packages/noob/src/noob/tube.py
      - packages/noob/src/noob/node/spec.py
      - packages/noob/src/noob/gui/**
  pull_request:
    paths:
      - js/**
      - packages/noob/src/noob/tube.py
      - packages/noob/src/noob/node/spec.py
      - packages/noob/src/noob/gui/**

jobs:
  # Code follows linter rules
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm --prefix js/ ci
      - name: Run ESLint
        run: npm --prefix js/ run lint

  # Code would be unchanged by formatting
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm --prefix js/ ci
      - name: Run ESLint
        run: npm --prefix js/ run format:check

  # Code still builds
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm --prefix js/ ci
      - name: Build main dist
        run: npm --prefix js/ run build
      - name: Build docs
        run: npm --prefix js/ run build:docs