name: Test Rust
on:
  push:
    branches:
      - main
    paths:
      - packages/noob-core/**
      - .github/workflows/tests-rust.yml
  pull_request:
    paths:
      - packages/noob-core/**
      - .github/workflows/tests-rust.yml

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/noob-core
      - name: Run cargo tests
        run: cargo test --manifest-path packages/noob-core/Cargo.toml
        timeout-minutes: 10
