name: Test JS
on:
  push:
    branches:
      - main
    paths:
      - js/**
      - packages/noob/src/noob/tube.py
      - packages/noob/src/noob/node/spec.py
      - packages/noob/src/noob/gui/**
  pull_request:
    paths:
      - js/**
      - packages/noob/src/noob/tube.py
      - packages/noob/src/noob/node/spec.py
      - packages/noob/src/noob/gui/**

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm --prefix js/ ci
      - name: Run vitest
        run: npm --prefix js/ run test